services:
  mysql:
    image: mysql:8.0
    container_name: access-management-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: access_management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
